stages:
  - build

build-frontend:
  stage: build
  only:
    changes:
      - frontend/*
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/frontend
