include:
  - template: Security/SAST.gitlab-ci.yml
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'
    
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  FRONTEND_ARTIFACT_PATH: $CI_REGISTRY_IMAGE/sausage-frontend:$VERSION
  FRONTEND_NOTIFICATION_DATA: |
    {
      "message": "Frontend #${VERSION} is ready, [download artifacts]($FRONTEND_ARTIFACT_PATH)"
    }

stages:
  - test
  - build
  - notify
  - deploy

cache:
  paths:
    - frontend/.npm/

spotbugs-sast:
  stage: test
  rules:
    - changes:
        - frontend/*

sonarqube-frontend:
  stage: test
  rules:
    - changes:
        - frontend/*
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend
    - >
      sonar-scanner 
      -Dsonar.qualitygate.wait=true
      -Dsonar.sources=.
      -Dsonar.projectKey=${SONAR_FRONTEND_PROJECT_KEY}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONARQUBE_LOGIN}

build-frontend:
  stage: build
  rules:
    - changes:
        - frontend/*
  needs:
    - spotbugs-sast
    - sonarqube-frontend      
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - >
      docker build
      --tag $CI_REGISTRY_IMAGE/sausage-frontend:$VERSION
      .
    - docker push $CI_REGISTRY_IMAGE/sausage-frontend:$VERSION

slack-notification-frontend:
  stage: notify
  needs:
    - build-frontend
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[notify]/
      changes:
        - frontend/*
  script:
    - 'curl --request POST --header "Content-type: application/json" --data "$FRONTEND_NOTIFICATION_DATA" "$WEBHOOK_URL"'

frontend-deploy:
  stage: deploy
  needs:
    - build-frontend
  image: argoproj/argocd:v2.3.3
  rules:
    - changes:
        - frontend/*
  script:
    - argocd --grpc-web --auth-token $ARGO_TOKEN --server $ARGO_SERVER app set sausage-store-std-011-009 -p frontend.image.tag=$VERSION
