version: "3.3"

services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend:${VERSION}
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=backend.sausage-store
    networks:
      - sausage-store
  backend-report:
    image: ${CI_REGISTRY_IMAGE}/sausage-report:${VERSION}
    container_name: sausage-store-backend-report
    env_file:
      - .env
    networks:
      - sausage-store
  frontend:
    image: ${CI_REGISTRY_IMAGE}/sausage-frontend:${VERSION}
    container_name: sausage-store-frontend
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store: 