include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  M2_REPO: ${CI_PROJECT_DIR}/.m2/repository
  BACKEND_NOTIFICATION_DATA: |
    {
      "blocks": [
        {
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": "Backend #${VERSION} is ready, <${NEXUS_REPO_URL}/sausage-store-pronin-konstantin-backend/com/yandex/practicum/devops/sausage-store/${VERSION}/sausage-store-${VERSION}.jar|download artifacts>."
          }
        }
      ]
    }

stages:
  - build
  - test
  - upload
  - notify

cache:
  paths:
    - ${M2_REPO}

build-backend:
  stage: build
  rules:
    - changes:
        - backend/*
  script:
    - cd backend
    - mvn -Dmaven.repo.local=${M2_REPO} -Dversion.application=${VERSION} package
  artifacts:
    paths:
      - backend/target/sausage-store-${VERSION}.jar

spotbugs-sast:
  stage: test
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 16
    MAVEN_REPO_PATH: ${M2_REPO}
  needs:
    - build-backend

sonarqube-backend:
  stage: test
  image: maven:3.8-openjdk-16
  script:
    - cd backend
    - >
      mvn verify sonar:sonar 
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectName=${SONAR_BACKEND_PROJECT_KEY}
      -Dsonar.projectKey=${SONAR_BACKEND_PROJECT_KEY}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONARQUBE_LOGIN}

upload-backend:
  stage: upload
  needs:
    - build-backend
  rules:
    - changes:
        - backend/*
  script:
    - cd backend
    - mvn -Dmaven.repo.local=${M2_REPO} -Dversion.application=${VERSION} -DskipTests -Dmaven.install.skip=true -s settings.xml deploy

slack-notification-backend:
  stage: notify
  needs:
    - upload-backend
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[notify]/
      changes:
        - backend/*
  script:
    - 'curl --request POST --header "Content-type: application/json" --data "$BACKEND_NOTIFICATION_DATA" "$WEBHOOK_URL"'
