variables:
  BACKEND_NOTIFICATION_DATA: |
    {
      "blocks": [
        {
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": "Backend is ready, <$BACKEND_ARTIFACT_PATH|download artifacts>."
          }
        }
      ]
    }

build-backend:
  stage: build
  rules:
    - changes:
        - backend/*
  script:
    - cd backend
    - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
    - echo "BACKEND_ARTIFACT_PATH=$CI_JOB_URL/artifacts/download" >> build.env
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1.jar
      - ${CI_PROJECT_DIR}/.m2/
    reports:
      dotenv: backend/build.env

sonarqube-backend:
  stage: test
  image: maven:3.8-openjdk-16
  script:
    - cd backend
    - >
      mvn verify sonar:sonar 
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectName=${SONAR_BACKEND_PROJECT_KEY}
      -Dsonar.projectKey=${SONAR_BACKEND_PROJECT_KEY}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONARQUBE_LOGIN}     

slack-notification-backend:
  stage: notify
  needs:
    - build-backend
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[notify]/
      changes:
        - backend/*
  script:
    - 'curl --request POST --header "Content-type: application/json" --data "$BACKEND_NOTIFICATION_DATA" "$WEBHOOK_URL"'
