include:
  - template: Security/SAST.gitlab-ci.yml
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'
    
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  BACKEND_REPORT_ARTIFACTS_URL: $CI_REGISTRY_IMAGE/sausage-report:$VERSION
  BACKEND_REPORT_NOTIFICATION_DATA: |
    {
      "message": "Backend-report #${VERSION} is ready, [download artifacts](${BACKEND_REPORT_ARTIFACTS_URL})."
    }

stages:
  - test
  - build
  - notify
  - deploy

spotbugs-sast:
  stage: test
  rules:
    - changes:
        - backend-report/*

unit-tests:
  stage: test
  rules:
  - changes:
      - backend-report/*  
  image: golang:1.14  
  script:
    - cd backend-report
    - go test ./app/services/health

build-backend-report:
  stage: build
  rules:
    - changes:
        - backend-report/*
  needs:
    - spotbugs-sast
    - unit-tests 
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd backend-report
    - >
      docker build
      --build-arg VERSION=${VERSION}
      --tag $CI_REGISTRY_IMAGE/sausage-report:$VERSION
      .
    - docker push $CI_REGISTRY_IMAGE/sausage-report:$VERSION

slack-notification-backend-report:
  stage: notify
  needs:
    - build-backend-report
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[notify]/
      changes:
        - backend-report/*
  script:
    - 'curl --request POST --header "Content-type: application/json" --data "$BACKEND_REPORT_NOTIFICATION_DATA" "$WEBHOOK_URL"'

backend-report-deploy:
  stage: deploy
  needs:
    - build-backend-report
  environment:
    name: production-backend-report
  rules:
    - when: manual
  image: vault:1.11.3  
  before_script:
    - apk add openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - export VAULT_CACERT=${CI_PROJECT_DIR}/vault.ca
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=sausage-store jwt=$CI_JOB_JWT)"
    - scp docker-compose.yml ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/docker-compose.yml
    - ssh ${DEV_USER}@${DEV_HOST}
      "export "VERSION=${VERSION}";
      export "VAULT_TOKEN=${VAULT_TOKEN}";
      export "PSQL_CONNECTION_STRING=${PSQL_CONNECTION_STRING}";
      export "PSQL_USER=$(vault kv get -field=passcode secret/psql.user)";
      export "PSQL_PASSWORD=$(vault kv get -field=passcode secret/psql.password)";
      export "MONGO_CONNECTION_STRING=$(vault kv get -field=passcode secret/mongo.connection.string)";
      export "CI_REGISTRY_USER=${CI_REGISTRY_USER}";
      export "CI_REGISTRY_PASSWORD=${CI_REGISTRY_PASSWORD}";
      export "CI_REGISTRY=${CI_REGISTRY}";
      export "CI_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE}";
      /bin/bash -s " < ./backend-report/deploy.sh
